services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass pharos
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /root/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pharos
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pharos
      - ME_CONFIG_MONGODB_SERVER=mongodb
