[package]
name = "api-server"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
# Workspace Crates
common = { workspace = true }
configs = { workspace = true }
service = { workspace = true }
pharos_interact = { workspace = true }


# Web Framework
salvo = { workspace = true }
salvo-oapi = { workspace = true }

# Async & Utilities
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
log4rs = { workspace = true }
lazy_static = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
once_cell = { workspace = true }

# Config
toml = { workspace = true }

# Web3 Auth
ethers = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
moka = { workspace = true }
jsonwebtoken = { workspace = true }

# Other (Keep if needed)
captcha = { workspace = true }
md5 = { workspace = true }
mongodb = { workspace = true }
redis = { workspace = true }
anyhow = { workspace = true }